spring:
  cloud:
    gateway:
       routes:
        - id: r1
          uri: http://localhost:8083/
          predicates:
             - Path=/users/**
        - id: r2
          uri: http://localhost:8081
          predicates:
            - Path=/articles/**
  application:
    name: ms-gateway
server:
  port: 8888